global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'market_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000'] # 도커 내부 실행 시
      # host.docker.internal은 맥/윈도우에서만 유효
      # 리눅스나 K8s에서는 IP/서비스명 수정 필요
